; This file for the FamiTone2 library and was generated by FamiStudio

_shatterhand_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument 00 (Bass)
	.word @env5, @env1, @env1
	.byte $00
	.byte $30 ;instrument 01 (BassDrum)
	.word @env10, @env4, @env1
	.byte $00
	.byte $30 ;instrument 02 (CymbalHigh)
	.word @env3, @env9, @env1
	.byte $00
	.byte $30 ;instrument 03 (CymbalLow)
	.word @env8, @env7, @env1
	.byte $00
	.byte $30 ;instrument 04 (Lead-Duty0)
	.word @env6, @env1, @env0
	.byte $00
	.byte $70 ;instrument 05 (Lead-Duty1)
	.word @env6, @env1, @env0
	.byte $00
	.byte $b0 ;instrument 06 (Lead-Duty2)
	.word @env6, @env1, @env0
	.byte $00
	.byte $30 ;instrument 07 (Snare)
	.word @env2, @env9, @env1
	.byte $00

@samples:
@env0:
	.byte $c0,$08,$c0,$04,$bd,$03,$bd,$00,$02
@env1:
	.byte $c0,$7f,$00,$00
@env2:
	.byte $ca,$c6,$c3,$c0,$00,$03
@env3:
	.byte $cb,$ca,$09,$c9,$00,$03
@env4:
	.byte $c0,$bf,$c1,$00,$02
@env5:
	.byte $cf,$7f,$00,$00
@env6:
	.byte $c8,$c9,$c5,$00,$02
@env7:
	.byte $c0,$c2,$c5,$00,$02
@env8:
	.byte $cb,$cb,$c5,$03,$c4,$03,$c3,$03,$c2,$00,$08
@env9:
	.byte $c0,$c1,$c2,$00,$02
@env10:
	.byte $cf,$ca,$c3,$c2,$c0,$00,$04
@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $88
@song0ref5:
	.byte $2c, $a1, $32, $8d, $2c, $2c, $a1, $36, $8d, $2c, $2c, $a1, $3c, $8d, $2c, $2c, $a1, $3a, $a1, $36, $8d, $3a, $32, $8d
	.byte $36, $28, $8d, $32
	.byte $ff, $1c
	.word @song0ref5
	.byte $00, $32, $8d, $4e, $8d, $28, $4a, $8d, $4e, $40, $8d, $4a, $4e, $8d, $40, $4a, $8d, $4e, $40, $8d, $4a, $36, $8d, $40
	.byte $32, $8d, $36, $28, $8d, $32, $3a, $8d, $28, $32, $8d, $3a, $28, $8d, $32, $22, $8d, $28
@song0ref78:
	.byte $28, $8d, $22, $2c, $8d, $28, $4e, $8d, $2c, $00, $2c, $8d, $3c, $8d, $4e, $00, $4e
@song0ref95:
	.byte $8d, $3c, $8f, $40, $8d, $3c, $00, $3c, $8d, $40, $8f, $3a, $8d, $40, $00, $40, $8d, $3a, $8f, $3c, $8d, $3a, $00, $3a
	.byte $8d, $36, $b3, $3a, $8d, $36, $00, $36, $8d, $32, $8d, $3a, $36, $d7, $00, $36, $8d, $22, $8d, $36, $28, $8d, $22, $2c
	.byte $8d, $28, $36, $8d, $2c, $32, $8d, $36, $28, $8d, $32, $2c, $8d, $28, $00, $28, $8d, $2c, $8f, $3c, $8d, $2c, $00, $2c
	.byte $ff, $43
	.word @song0ref95
	.byte $8a
@song0ref171:
	.byte $46, $b3, $4a, $8d, $46, $4e, $8d, $4a, $52, $8d, $4e, $54, $a1, $58, $8d, $54, $54, $8d, $58, $00, $58, $8d, $4c, $b3
	.byte $46, $c5, $52, $93, $46, $4e, $93, $52, $4c, $93, $4e, $4e, $a1, $44, $8d, $4e, $54, $a1, $52, $8d, $54, $4e, $8d, $52
	.byte $4a, $8d, $4e, $00, $4e, $8d, $4a, $8f
	.byte $ff, $0b
	.word @song0ref171
	.byte $4a, $a1, $4e, $8d, $4a, $52, $8d, $4e, $00, $4e, $8d, $54, $b3, $58, $c5, $58, $8f, $5c, $8d, $58, $62, $8d, $5c, $58
	.byte $8d, $62, $00, $62, $8d, $88, $3c, $8d, $58, $3a, $8d, $3c, $32, $8d, $3a, $24, $8d, $32, $22, $8d, $24
	.byte $ff, $59
	.word @song0ref78
	.byte $ff, $43
	.word @song0ref95
	.byte $4a, $a1, $4a, $8f, $4e, $8d, $4a, $52, $8d, $4e, $52, $b3, $52, $8f, $4e, $8d, $52, $00, $52, $8d, $4c, $b3, $4e, $c5
	.byte $4e, $8f, $52, $8d, $4e, $54, $8d, $52, $58, $b3, $54, $8d, $58, $52, $8d, $54, $00, $54, $8d, $4e, $b3, $00, $4e, $9f
@song0ref329:
	.byte $52, $a1, $52, $8f, $54, $8d, $52, $58, $8d, $54, $5c, $b3, $58, $8d, $5c, $54, $8d, $58, $00, $58, $8d, $58, $8d, $54
	.byte $54, $8d, $58, $52, $8d, $54, $4c, $c5, $4e, $c5, $52, $8d, $4e, $52, $8f, $00, $52, $8d, $52, $d7, $5c, $8d, $52
@song0ref376:
	.byte $4e, $8d, $5c, $44, $8d, $4e, $58, $8d, $44, $4a, $8d, $58, $40, $8d, $4a, $3c, $a1, $00, $3c, $8d, $3c, $8f, $3a, $8d
	.byte $3c, $32, $8d, $3a, $3c, $8d, $32, $3a, $8d, $3c, $32, $8d, $3a, $36, $8d, $32, $3c, $8d, $36, $3c, $8f, $00, $3c, $8d
	.byte $40, $8d, $3c, $40, $8f, $00, $40, $8d, $3c, $8d, $40, $3c, $8f, $00, $3c, $8d, $40, $89, $41, $3c, $40, $8f, $00, $40
	.byte $8d, $4e, $8d, $40, $4a, $8d, $4e, $46, $8d, $4a, $44, $8d, $46, $5c, $8d, $44
	.byte $ff, $55
	.word @song0ref376
	.byte $2e, $a1, $3c, $8d, $2e, $32, $a1, $40, $a1, $36, $a1, $44, $a1, $52, $8d, $44, $54, $8d, $52, $8f, $54, $4e, $8d, $52
	.byte $4a, $8d, $4e, $54, $8d, $4a, $54, $8f, $00, $54, $8d, $52, $8d, $54, $52, $8f, $00, $52, $8d, $54, $8d, $52, $54, $8f
	.byte $00, $54, $8d, $22, $8d, $54, $2c, $8d, $22, $3a, $8d, $2c, $4a, $8d, $3a, $52, $b3, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $8a
@song0ref537:
	.byte $36, $a1, $3c, $8d, $36, $36, $a1, $40, $8d, $36, $36, $a1, $44, $8d, $36, $36, $a1, $40, $a1, $3c, $8d, $40, $3a, $8d
	.byte $3c, $32, $8d, $3a
	.byte $ff, $1c
	.word @song0ref537
	.byte $00, $3a, $8d, $54, $8d, $32
@song0ref574:
	.byte $52, $8d, $54, $4a, $8d, $52, $54, $8d, $4a
@song0ref583:
	.byte $52, $8d, $54, $4a, $8d, $52, $3c, $8d, $4a, $3a, $8d, $3c, $32, $8d, $3a, $40, $8d, $32, $3a, $8d, $40, $32, $8d, $3a
	.byte $2c, $8d, $32, $32, $8d, $2c
@song0ref613:
	.byte $36, $8d, $32, $66, $8d, $36, $00, $36, $8d, $44, $8d, $66, $00, $66
@song0ref627:
	.byte $8d, $44, $8f, $46, $8d, $44, $00, $44, $8d, $46, $8f, $40, $8d, $46, $00, $46, $8d, $40, $8f, $44, $8d, $40, $00, $40
	.byte $8d, $3c, $b3, $40, $8d, $3c, $00, $3c, $8d, $3a, $8d, $40, $3c, $d7, $00, $3c, $8d, $2c, $8d, $3c, $32, $8d, $2c, $36
	.byte $8d, $32, $3c, $8d, $36, $3a, $8d, $3c, $32, $8d, $3a, $36, $8d, $32, $00, $32, $8d, $36, $8f, $44, $8d, $36, $00, $36
	.byte $ff, $43
	.word @song0ref627
	.byte $8c
@song0ref703:
	.byte $4e, $b3, $52, $8d, $4e, $54, $8d, $52, $58, $8d, $54, $5c, $a1, $5e, $8d, $5c, $5c, $8d, $5e, $00, $5e, $8d, $52, $b3
	.byte $58, $c5, $58, $95, $54, $93, $58, $52, $93, $54, $54, $a1, $4e, $8d, $54, $5c, $d7, $00, $5c, $9f
	.byte $ff, $10
	.word @song0ref703
	.byte $62, $8d, $5e, $00, $5e, $8d, $66, $b3, $6a, $c5, $6a, $8f, $6c, $8d, $6a, $70, $8d, $6c, $6a, $8d, $70, $00, $70, $8d
	.byte $8a, $54, $8d, $6a
	.byte $ff, $0f
	.word @song0ref583
	.byte $ff, $56
	.word @song0ref613
	.byte $ff, $43
	.word @song0ref627
	.byte $ff, $15
	.word @song0ref329
	.byte $52, $b3, $54, $c5, $54, $8f, $58, $8d, $54, $5c, $8d, $58, $5e, $b3, $5c, $8d, $5e, $58, $8d, $5c, $00, $5c, $8d, $54
	.byte $b3, $00, $54, $9f, $58, $a1, $58, $8f, $5c, $8d, $58, $5e, $8d, $5c, $62, $b3, $5e, $8d, $62, $5c, $8d, $5e, $00, $5e
	.byte $8d, $5e, $8d, $5c, $5c, $8d, $5e, $58, $8d, $5c, $5c, $c5, $60, $c5, $62, $8d, $60, $62, $8f, $00, $62, $8d, $64, $d7
	.byte $66, $8d, $64
@song0ref865:
	.byte $5c, $8d, $66, $4e, $8d, $5c, $62, $8d, $4e, $58, $8d, $62, $4a, $8d, $58, $46, $a1, $00, $46, $8d, $54, $8d, $46
	.byte $ff, $0f
	.word @song0ref574
@song0ref891:
	.byte $4e, $8d, $4a, $46, $8d, $4e, $46, $8f, $00, $46, $8d, $4a, $8d, $46, $4a, $8f, $00, $4a, $8d, $4e, $8d, $4a, $4e, $8f
	.byte $00, $4e, $8d, $52, $8d, $4e, $52, $8f, $00, $52, $8d, $54, $8d, $52, $52, $8d, $54, $4e, $8d, $52, $4a, $8d, $4e, $66
	.byte $8d, $4a
	.byte $ff, $17
	.word @song0ref865
	.byte $ff, $0f
	.word @song0ref574
	.byte $ff, $2f
	.word @song0ref891
	.byte $46, $a1, $54, $8d, $46, $4a, $a1, $58, $a1, $4e, $a1, $5c, $a1, $6a, $8d, $5c, $6c, $8d, $6a, $6a, $8d, $6c, $66, $8d
	.byte $6a, $62, $8d, $66, $66, $8d, $62, $66, $8f, $00, $66, $8d, $62, $8d, $66, $62, $8f, $00, $62, $8d, $66, $8d, $62, $66
	.byte $8f, $00, $66, $8d, $2c, $8d, $66, $3a, $8d, $2c, $44, $8d, $3a, $52, $8d, $44, $5c, $b3, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref1021:
	.byte $36, $8b, $01, $36, $8b, $01, $36, $8b, $01, $36, $8b, $01
	.byte $ff, $0c
	.word @song0ref1021
@song0ref1036:
	.byte $36, $8b, $01, $36, $8b, $01, $36, $8b, $01, $32, $9d, $01, $2c, $8b, $01, $32, $8b, $01, $3a, $8b, $00, $81
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $16
	.word @song0ref1036
	.byte $32, $f7, $01, $32, $d3, $01, $32, $8b, $01, $2c, $8b, $01, $32, $8b, $01, $36, $8b, $00, $81
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $0b
	.word @song0ref1021
	.byte $00, $81
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $0c
	.word @song0ref1021
@song0ref1106:
	.byte $36
@song0ref1107:
	.byte $8b, $01, $2c, $8b, $01, $32, $8b, $01, $36, $8b, $01, $3c, $8b, $01, $3a, $8b, $01, $32, $8b, $01, $36, $8b
@song0ref1129:
	.byte $00, $81
@song0ref1131:
	.byte $2e
@song0ref1132:
	.byte $8b, $01, $2e, $8b, $01, $2e, $8b, $01, $2e, $8b, $01
	.byte $ff, $0c
	.word @song0ref1131
	.byte $ff, $0c
	.word @song0ref1131
	.byte $ff, $0b
	.word @song0ref1131
	.byte $ff, $0e
	.word @song0ref1129
	.byte $ff, $0c
	.word @song0ref1131
	.byte $2e
	.byte $ff, $18
	.word @song0ref1107
@song0ref1162:
	.byte $28, $8b, $01, $28, $8b, $01, $36, $8b, $01, $3c, $8b, $01
	.byte $ff, $0c
	.word @song0ref1162
@song0ref1177:
	.byte $2c, $8b, $01, $2c, $8b, $01, $3a, $8b, $01, $40, $8b, $01
	.byte $ff, $0b
	.word @song0ref1177
	.byte $00, $81
	.byte $ff, $0c
	.word @song0ref1162
	.byte $ff, $0c
	.word @song0ref1177
@song0ref1200:
	.byte $36, $8b, $01, $36, $8b, $01, $32, $8b, $01, $32, $8b, $01, $2e, $8b, $01, $2e, $8b, $01, $2c, $8b, $01, $2c, $8b, $00
	.byte $81
	.byte $ff, $0c
	.word @song0ref1162
	.byte $ff, $0c
	.word @song0ref1162
	.byte $ff, $0c
	.word @song0ref1177
	.byte $ff, $0b
	.word @song0ref1177
	.byte $00, $81, $2e, $8b, $01, $2e, $8b, $01, $3c, $8b, $01, $46, $8b, $01, $2e, $8b, $01, $3c, $8b, $01, $46, $8b, $01, $32
	.byte $8b, $00, $93, $32, $8b, $01, $32, $9d, $01, $32, $8b, $01, $32, $9d, $01, $36, $8b, $00, $81
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $0b
	.word @song0ref1021
	.byte $00, $81
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $25
	.word @song0ref1106
	.byte $ff, $0c
	.word @song0ref1131
	.byte $ff, $0c
	.word @song0ref1131
	.byte $ff, $0b
	.word @song0ref1131
	.byte $ff, $0e
	.word @song0ref1129
	.byte $ff, $0c
	.word @song0ref1131
	.byte $2e
	.byte $ff, $18
	.word @song0ref1107
@song0ref1322:
	.byte $32
@song0ref1323:
	.byte $8b, $01, $32, $8b, $01, $32, $8b, $01, $32, $8b, $01
	.byte $ff, $0c
	.word @song0ref1322
@song0ref1337:
	.byte $34, $8b, $01, $34, $8b, $01, $34, $8b, $01, $34, $8b, $01
	.byte $ff, $0b
	.word @song0ref1337
	.byte $00, $81
	.byte $ff, $0c
	.word @song0ref1021
	.byte $ff, $0c
	.word @song0ref1021
@song0ref1360:
	.byte $38, $8b, $01, $38, $8b, $01, $38, $8b, $01, $38, $8b, $01
	.byte $ff, $0b
	.word @song0ref1360
	.byte $00, $81
@song0ref1377:
	.byte $3a, $8b, $01, $3a, $8b, $01, $3a, $8b, $01, $3a, $8b, $01
	.byte $ff, $0c
	.word @song0ref1377
	.byte $ff, $0c
	.word @song0ref1322
	.byte $ff, $0b
	.word @song0ref1322
	.byte $00, $81
@song0ref1400:
	.byte $2c
@song0ref1401:
	.byte $8b, $01, $2c, $8b, $01, $2c, $8b, $01, $2c, $8b, $01
	.byte $ff, $0c
	.word @song0ref1400
	.byte $2c, $8b, $01, $2c, $8b, $01, $3a, $8b, $01, $44, $9d, $01, $44, $8b, $01, $3a, $8b, $01, $2c, $8b, $00, $81, $36, $8b
	.byte $01
	.byte $ff, $0c
	.word @song0ref1200
@song0ref1443:
	.byte $32, $8b, $01, $2e, $af, $01, $2e, $8b, $01, $2e, $9d, $01, $2e, $8b, $01, $2e, $9d, $01, $2e, $8b, $00, $81, $28, $8b
	.byte $01, $28, $8b, $01, $28
	.byte $ff, $0b
	.word @song0ref1401
	.byte $2e, $8b, $01, $2e, $8b, $01, $2e
	.byte $ff, $0b
	.word @song0ref1323
@song0ref1485:
	.byte $2e, $8b, $01, $2e, $8b, $01, $32, $8b, $01, $32, $8b, $00, $81, $36, $8b, $01
	.byte $ff, $0c
	.word @song0ref1200
	.byte $ff, $1d
	.word @song0ref1443
	.byte $ff, $0b
	.word @song0ref1401
	.byte $2e, $8b, $01
	.byte $ff, $0b
	.word @song0ref1485
	.byte $01, $32, $8b, $01
	.byte $ff, $0d
	.word @song0ref1485
	.byte $28, $8b, $01, $28, $8b, $01, $28, $8b, $01, $28
	.byte $ff, $0b
	.word @song0ref1401
	.byte $2c
	.byte $ff, $0b
	.word @song0ref1132
	.byte $2e
	.byte $ff, $0b
	.word @song0ref1323
	.byte $32, $8b, $00, $81, $36, $8b, $01, $36, $8b, $00, $93, $32, $8b, $01, $32, $8b, $00, $93, $36, $8b, $01, $36, $8b, $00
	.byte $93
	.byte $ff, $0c
	.word @song0ref1400
	.byte $2c, $8b, $01, $30, $8b, $01, $34, $8b, $00, $81, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref1586:
	.byte $84, $5a, $a1, $86, $4e, $a1, $84, $5a, $a1, $86, $4e, $a1, $84, $5a, $a1, $86, $4e, $a1
	.byte $ff, $0c
	.word @song0ref1586
	.byte $84, $5a, $a1, $86, $4e, $a1, $84, $5a, $a1, $86, $4e, $a1, $84, $5a, $a1, $5a, $a1, $5a, $a1, $5a, $a1, $5a, $a1, $5a
	.byte $a1, $86, $4e, $8f, $84, $5a, $8f, $86, $4f, $4e, $8b, $84
@song0ref1643:
	.byte $5a
@song0ref1644:
	.byte $8f, $82, $42, $8f, $8e, $5a, $8f, $86, $4e, $8f, $8e, $5a, $8f, $82, $42, $8f, $42, $8f, $86, $4e, $8f, $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
@song0ref1673:
	.byte $8e, $5a, $8f, $82, $42, $8f, $86, $4e, $8f, $4e, $8f, $82, $42, $8f, $86, $4e, $8f, $4e, $8f, $82, $42, $8f, $86, $4e
	.byte $ff, $0f
	.word @song0ref1644
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $ff, $11
	.word @song0ref1673
	.byte $ff, $0f
	.word @song0ref1644
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e, $5a, $8f, $86, $4e, $8f, $82, $42, $8f
@song0ref1747:
	.byte $42, $8f, $86, $4e, $8f, $82, $42, $8f, $86, $4e, $8f, $4e, $8f, $4e
	.byte $ff, $0f
	.word @song0ref1644
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $ff, $11
	.word @song0ref1673
	.byte $ff, $0f
	.word @song0ref1644
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $ff, $11
	.word @song0ref1673
	.byte $ff, $0f
	.word @song0ref1644
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e
	.byte $ff, $10
	.word @song0ref1643
	.byte $8e, $5a, $8f, $86, $4e, $8f, $4e, $8f, $82
	.byte $ff, $0b
	.word @song0ref1747
	.byte $8f
@song0ref1829:
	.byte $4e, $8f, $4e, $a1, $4e, $8f, $4e, $a1, $4e, $8f, $4e, $a1, $82, $42, $8f, $86, $4e, $8f, $82, $42, $8f, $86, $4e, $8f
	.byte $82, $42, $8f, $86, $4e, $8f, $4e
@song0ref1860:
	.byte $8f, $82, $42, $8f, $42, $8f, $84, $5a, $8f, $82, $42, $8f, $42, $8f, $84, $5a
	.byte $ff, $0c
	.word @song0ref1860
	.byte $8f, $86, $4e, $a1, $4e, $a1
	.byte $ff, $25
	.word @song0ref1829
	.byte $ff, $0c
	.word @song0ref1860
	.byte $8f, $86, $4e, $a1, $4e, $a1
	.byte $ff, $0c
	.word @song0ref1586
	.byte $84, $5a, $a1, $86, $4e, $a1
	.byte $ff, $0c
	.word @song0ref1829
	.byte $4e, $8f, $4e, $8f, $4e, $8f, $4e, $8f, $4e, $8f, $82, $42, $8f, $42, $8f, $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref1928:
	.byte $f9, $f9, $ab, $f9, $f9, $ab, $f9, $f9, $ab, $f9, $f9, $ab
	.byte $ff, $0c
	.word @song0ref1928
	.byte $ff, $0c
	.word @song0ref1928
	.byte $ff, $0c
	.word @song0ref1928
	.byte $ff, $0c
	.word @song0ref1928
	.byte $ff, $0c
	.word @song0ref1928
	.byte $f9, $f9, $ab, $fd
	.word @song0ch4loop
