;this file for FamiTone2 library generated by text2data tool

_the_moon_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ; 00 : Bass
	.word @env0, @env4, @env4
	.byte $00
	.byte $f0 ; 01 : Bleep
	.word @env3, @env4, @env4
	.byte $00
	.byte $70 ; 02 : BleepIntro
	.word @env9, @env4, @env4
	.byte $00
	.byte $30 ; 03 : DrumHi
	.word @env10, @env4, @env4
	.byte $00
	.byte $30 ; 04 : DrumIntro
	.word @env8, @env4, @env4
	.byte $00
	.byte $30 ; 05 : DrumLo
	.word @env7, @env4, @env4
	.byte $00
	.byte $30 ; 06 : DrumMed
	.word @env1, @env4, @env4
	.byte $00
	.byte $30 ; 07 : Lead
	.word @env2, @env4, @env4
	.byte $00
	.byte $f0 ; 08 : LeadIntro
	.word @env6, @env4, @env4
	.byte $00
	.byte $30 ; 09 : LeadLo
	.word @env5, @env4, @env4
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $ca,$02,$c6,$03,$c2,$00,$04
@env2:
	.byte $ca,$7f,$00,$00
@env3:
	.byte $c7,$02,$c5,$03,$c1,$00,$04
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $c7,$7f,$00,$00
@env6:
	.byte $c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$00,$09
@env7:
	.byte $ca,$02,$c2,$00,$02
@env8:
	.byte $ca,$02,$c5,$00,$02
@env9:
	.byte $c7,$06,$c1,$00,$02
@env10:
	.byte $ca,$c4,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01, $f9, $f9, $b7, $90, $4c, $f9, $b5, $00, $56, $a3, $00, $5a, $a3, $00, $60, $a3, $00, $60, $b7, $00, $5e, $8f
	.byte $00, $5e, $f9, $8d, $00, $5a, $a3, $00, $56, $a3, $00, $64, $f3, $00, $56, $f3, $00, $6e, $b9, $f9, $f3, $00, $72, $a3
	.byte $00, $6e, $8f, $00, $7c, $f9, $f9, $c7, $00
@song0ch0loop:
	.byte $cf, $8e, $46, $8f, $00, $48, $8f, $00, $4c, $8f, $00, $4c, $b7, $00, $56, $a3, $00, $54, $a3, $00, $56, $a3, $00, $5a
	.byte $a3, $00, $5e, $8f, $00, $56, $f9, $dd, $00, $54, $8f, $00, $56, $8f, $00, $64, $b7, $00, $56, $8f, $00, $56, $f9, $dd
	.byte $00, $56, $8f, $00, $56, $cb, $00, $93, $5a, $8f, $00, $56, $8f, $00, $54, $f9, $b5, $00, $46, $cb, $00, $93, $42, $8f
	.byte $00, $3e, $8f, $00, $4c, $cb, $00, $93, $56, $a3, $00, $5a, $a3, $00, $60, $b7, $00, $5e, $8f, $00, $5e, $f9, $a1, $00
	.byte $64, $a3, $00, $60, $a3, $00, $5e, $8f, $00, $60, $8f, $00, $5e, $8f, $00, $56, $a3, $00, $4c, $cb, $00, $5a, $8f, $00
	.byte $56, $8f, $00, $54, $8f, $00, $50, $8f, $00, $54, $b7, $00, $56, $8f, $00, $a7, $56, $8f, $00, $a7, $56, $a3, $00, $8d
	.byte $2e, $f9, $93, $00
@song0ref207:
	.byte $56, $8f, $00, $56, $8f, $00, $a7, $5a, $8f, $00, $5a, $8f, $00, $93, $52, $cb, $00, $4c, $a3, $00, $52, $8f, $00, $48
	.byte $83, $4a, $83, $00, $49, $00, $44, $8f, $00, $48, $a3, $00, $44, $8f, $00, $48, $8f, $00, $93, $44, $8f, $00, $93, $4c
	.byte $f9, $a1, $00, $93
	.byte $ff, $0e
	.word @song0ref207
	.byte $5c, $a3, $00, $52, $a3, $00, $52, $a3, $00, $52, $8f, $00, $5c, $8f, $00, $60, $91, $f5, $00, $5c, $8f, $00, $64, $f3
	.byte $00, $64, $8f, $00, $64, $8f, $00, $64, $91, $f9, $f3, $00, $1e, $a3, $00, $22, $a3, $00, $fd
	.word @song0ch0loop
@song0ch1:
	.byte $84
@song0ref308:
	.byte $56, $8f, $00, $64, $8f, $00, $6e, $8f, $00, $72, $8f, $00, $64, $8f, $00, $6e, $8f, $00, $72
@song0ref327:
	.byte $8f, $00, $78, $8f, $00, $64, $8f, $00, $78, $8f, $00, $76, $8f, $00, $64, $8f, $00, $76, $8f, $00, $72, $8f, $00, $6e
	.byte $8f, $00
	.byte $ff, $2d
	.word @song0ref308
	.byte $ff, $2d
	.word @song0ref308
	.byte $ff, $2d
	.word @song0ref308
	.byte $ff, $2d
	.word @song0ref308
	.byte $82
	.byte $ff, $15
	.word @song0ref308
	.byte $64
	.byte $ff, $1a
	.word @song0ref327
@song0ch1loop:
	.byte $ff, $15
	.word @song0ref308
	.byte $64
	.byte $ff, $1a
	.word @song0ref327
	.byte $ff, $15
	.word @song0ref308
	.byte $64
	.byte $ff, $1a
	.word @song0ref327
	.byte $ff, $15
	.word @song0ref308
	.byte $64
	.byte $ff, $1a
	.word @song0ref327
	.byte $ff, $15
	.word @song0ref308
	.byte $64
	.byte $ff, $1a
	.word @song0ref327
	.byte $ff, $15
	.word @song0ref308
	.byte $64
	.byte $ff, $1a
	.word @song0ref327
	.byte $ff, $15
	.word @song0ref308
	.byte $64
	.byte $ff, $1a
	.word @song0ref327
	.byte $ff, $15
	.word @song0ref308
	.byte $64
	.byte $ff, $1a
	.word @song0ref327
	.byte $6e, $8f, $00, $5c, $8f, $00, $66, $8f, $00, $72, $8f, $00, $60, $8f, $00, $72, $8f, $00, $78, $8f, $00, $76, $8f, $00
	.byte $6e, $8f, $00, $64, $8f, $00, $60, $8f, $00, $5e, $8f, $00, $56, $8f, $00, $4c, $8f, $00, $48, $8f, $00, $46, $8f, $00
	.byte $92, $44, $8f, $00, $44, $8f, $00, $a7, $48, $8f, $00, $48, $8f, $00, $93, $44, $a3, $00, $84, $5a, $8f, $00, $5c, $8f
	.byte $00, $6a, $8f, $00, $93, $72, $8f, $00, $74, $8f, $00, $02, $8f, $00, $92, $36, $a3, $00, $36, $8f, $00, $36, $8f, $00
	.byte $93, $36, $8f, $00, $93, $3c, $f9, $a1, $00, $93, $4e, $8f, $00, $4e, $8f, $00, $a7, $48, $8f, $00, $48, $8f, $00, $93
	.byte $4c, $a3, $00, $4c, $a3, $00, $4c, $a3, $00, $4c, $8f, $00, $52, $8f, $00, $56, $91, $e1, $00, $93, $56, $8f, $00, $54
	.byte $f3, $00, $54, $8f, $00, $54, $8f, $00, $56, $8f, $00, $82
	.byte $ff, $15
	.word @song0ref308
	.byte $64
	.byte $ff, $1a
	.word @song0ref327
	.byte $fd
	.word @song0ch1loop
@song0ch2:
	.byte $f9, $f9, $b7, $80, $3e, $b7, $00, $4c, $b7, $00, $56, $f9, $a1, $00, $93, $3a, $b7, $00, $48, $b7, $00, $52, $f9, $a1
	.byte $00, $93, $38, $b7, $00, $46, $b7, $00, $50, $f9, $a1, $00, $93, $36, $b7, $00, $44, $b7, $00, $4e, $f9, $a1, $00, $93
@song0ref637:
	.byte $56, $8f, $00, $56, $8f, $00, $56, $8f, $00, $56, $8f, $00
	.byte $ff, $0c
	.word @song0ref637
	.byte $ff, $0c
	.word @song0ref637
	.byte $ff, $0c
	.word @song0ref637
@song0ch2loop:
	.byte $ff, $0c
	.word @song0ref637
	.byte $ff, $0c
	.word @song0ref637
@song0ref665:
	.byte $54, $8f, $00, $54, $8f, $00, $54, $8f, $00, $54, $8f, $00
	.byte $ff, $0c
	.word @song0ref665
@song0ref680:
	.byte $50, $8f, $00, $50, $8f, $00, $50, $8f, $00, $50, $8f, $00
	.byte $ff, $0c
	.word @song0ref680
@song0ref695:
	.byte $4c, $8f, $00, $4c, $8f, $00, $4c, $8f, $00, $4c, $8f, $00
	.byte $ff, $0c
	.word @song0ref695
@song0ref710:
	.byte $48, $8f, $00, $48, $8f, $00, $48, $8f, $00, $48, $8f, $00
	.byte $ff, $0c
	.word @song0ref710
@song0ref725:
	.byte $4a, $8f, $00, $4a, $8f, $00, $4a, $8f, $00, $4a, $8f, $00
	.byte $ff, $0c
	.word @song0ref725
	.byte $ff, $0c
	.word @song0ref695
	.byte $ff, $0c
	.word @song0ref695
	.byte $ff, $0c
	.word @song0ref695
	.byte $ff, $0c
	.word @song0ref695
	.byte $ff, $0c
	.word @song0ref637
	.byte $ff, $0c
	.word @song0ref637
@song0ref758:
	.byte $52, $8f, $00, $52, $8f, $00, $52, $8f, $00, $52, $8f, $00
	.byte $ff, $0c
	.word @song0ref758
	.byte $ff, $0c
	.word @song0ref680
	.byte $ff, $0c
	.word @song0ref680
@song0ref779:
	.byte $4e, $8f, $00, $4e, $8f, $00, $4e, $8f, $00, $4e, $8f, $00
	.byte $ff, $0c
	.word @song0ref779
	.byte $ff, $0c
	.word @song0ref695
	.byte $ff, $0c
	.word @song0ref695
	.byte $ff, $0c
	.word @song0ref725
	.byte $ff, $0c
	.word @song0ref695
	.byte $4e, $8f, $00, $a7, $52, $8f, $00, $a7, $56, $b7, $00, $3e, $8f, $00, $3e, $8f, $00, $3e, $8f, $00, $3e, $8f, $00, $3e
	.byte $8f, $00, $3e, $8f, $00, $3e, $8f, $00
@song0ref838:
	.byte $48, $8f, $00, $48, $8f, $00, $a7, $52, $8f, $00, $52, $8f, $00, $93, $44, $a3, $00, $44, $8f, $00, $44, $8f, $00, $44
	.byte $8f, $00, $44, $8f, $00, $44, $8f, $00, $44, $8f, $00, $44, $8f, $00
	.byte $ff, $0c
	.word @song0ref710
	.byte $ff, $0c
	.word @song0ref710
	.byte $ff, $0c
	.word @song0ref695
	.byte $ff, $0c
	.word @song0ref695
	.byte $ff, $26
	.word @song0ref838
	.byte $ff, $0c
	.word @song0ref710
	.byte $ff, $0c
	.word @song0ref710
	.byte $ff, $0c
	.word @song0ref695
	.byte $ff, $0c
	.word @song0ref695
	.byte $ff, $0c
	.word @song0ref779
	.byte $ff, $0c
	.word @song0ref779
	.byte $4e, $8f, $00, $bb, $4e, $a3, $00, $52, $a3, $00, $fd
	.word @song0ch2loop
@song0ch3:
@song0ref922:
	.byte $f9, $f9, $b7, $f9, $f9, $b7, $f9, $f9, $b7, $f9, $f9, $b7, $f9, $e1, $88, $4a, $8b, $00, $83, $40, $8b, $00, $83, $4a
	.byte $8b, $00, $83, $40, $8b, $00, $83
@song0ref953:
	.byte $8a, $40, $8b, $00, $83, $86, $58, $83, $00, $8b, $8c, $4a, $8f, $00, $86, $58, $83, $00, $8b
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
@song0ref978:
	.byte $8a, $40, $8b, $00, $83, $86, $58, $83, $00, $8b, $8c, $4a, $8f, $00, $4a, $8f, $00
@song0ch3loop:
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0f
	.word @song0ref953
	.byte $ff, $0e
	.word @song0ref978
	.byte $fd
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $0d
	.word @song0ref922
	.byte $f9, $b7, $f9, $f9, $cb
@song0ch4loop:
@song0ref1164:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $0c
	.word @song0ref1164
	.byte $ff, $0c
	.word @song0ref1164
	.byte $f9, $f9, $cb, $fd
	.word @song0ch4loop
